### ISSUE TITLE
Folder Missing?

### ISSUE THREAD

**Issue by BoGrumpus** [RaiderKnight/RK-Vin-Base#1]
I see an extras folder here, but the main RK_Vin_Base folder is missing...

**Comment by RaiderKnight** [comment]
The file is missing because as it is written on the homepage of this mod, it is now available via LifePlay Mods Flix.

**Comment by RaiderKnight** [comment]
So, I'm closing this issue! LifePlay Mods Flix can be found here: [https://github.com/RaiderKnight/RK-LifePlay-Mods-Flix](https://github.com/RaiderKnight/RK-LifePlay-Mods-Flix)
